In [2]:
import pandas as pd

In [10]:
data = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data')

In [11]:
data.columns=['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm','Species']

In [13]:
data.describe()

       SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count     149.000000    149.000000     149.000000    149.000000
mean        5.848322      3.051007       3.774497      1.205369
std         0.828594      0.433499       1.759651      0.761292
min         4.300000      2.000000       1.000000      0.100000
25%         5.100000      2.800000       1.600000      0.300000
50%         5.800000      3.000000       4.400000      1.300000
75%         6.400000      3.300000       5.100000      1.800000
max         7.900000      4.400000       6.900000      2.500000

In [14]:
data.head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            4.9           3.0            1.4           0.2  Iris-setosa
1            4.7           3.2            1.3           0.2  Iris-setosa
2            4.6           3.1            1.5           0.2  Iris-setosa
3            5.0           3.6            1.4           0.2  Iris-setosa
4            5.4           3.9            1.7           0.4  Iris-setosa

In [15]:
data

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              4.9           3.0            1.4           0.2     Iris-setosa
1              4.7           3.2            1.3           0.2     Iris-setosa
2              4.6           3.1            1.5           0.2     Iris-setosa
3              5.0           3.6            1.4           0.2     Iris-setosa
4              5.4           3.9            1.7           0.4     Iris-setosa
5              4.6           3.4            1.4           0.3     Iris-setosa
6              5.0           3.4            1.5           0.2     Iris-setosa
7              4.4           2.9            1.4           0.2     Iris-setosa
8              4.9           3.1            1.5           0.1     Iris-setosa
9              5.4           3.7            1.5           0.2     Iris-setosa
10             4.8           3.4            1.6           0.2     Iris-setosa
11             4.8           3.0            1.4           0.1     Iris-setosa
12             4.3           3.0            1.1           0.1     Iris-setosa
13             5.8           4.0            1.2           0.2     Iris-setosa
14             5.7           4.4            1.5           0.4     Iris-setosa
15             5.4           3.9            1.3           0.4     Iris-setosa
16             5.1           3.5            1.4           0.3     Iris-setosa
17             5.7           3.8            1.7           0.3     Iris-setosa
18             5.1           3.8            1.5           0.3     Iris-setosa
19             5.4           3.4            1.7           0.2     Iris-setosa
20             5.1           3.7            1.5           0.4     Iris-setosa
21             4.6           3.6            1.0           0.2     Iris-setosa
22             5.1           3.3            1.7           0.5     Iris-setosa
23             4.8           3.4            1.9           0.2     Iris-setosa
24             5.0           3.0            1.6           0.2     Iris-setosa
25             5.0           3.4            1.6           0.4     Iris-setosa
26             5.2           3.5            1.5           0.2     Iris-setosa
27             5.2           3.4            1.4           0.2     Iris-setosa
28             4.7           3.2            1.6           0.2     Iris-setosa
29             4.8           3.1            1.6           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
119            6.9           3.2            5.7           2.3  Iris-virginica
120            5.6           2.8            4.9           2.0  Iris-virginica
121            7.7           2.8            6.7           2.0  Iris-virginica
122            6.3           2.7            4.9           1.8  Iris-virginica
123            6.7           3.3            5.7           2.1  Iris-virginica
124            7.2           3.2            6.0           1.8  Iris-virginica
125            6.2           2.8            4.8           1.8  Iris-virginica
126            6.1           3.0            4.9           1.8  Iris-virginica
127            6.4           2.8            5.6           2.1  Iris-virginica
128            7.2           3.0            5.8           1.6  Iris-virginica
129            7.4           2.8            6.1           1.9  Iris-virginica
130            7.9           3.8            6.4           2.0  Iris-virginica
131            6.4           2.8            5.6           2.2  Iris-virginica
132            6.3           2.8            5.1           1.5  Iris-virginica
133            6.1           2.6            5.6           1.4  Iris-virginica
134            7.7           3.0            6.1           2.3  Iris-virginica
135            6.3           3.4            5.6           2.4  Iris-virginica
136            6.4           3.1            5.5           1.8  Iris-virginica
137            6.0           3.0            4.8           1.8  Iris-virginica
138            6.9           3.1            5.4           2.1  Iris-virginica
139            6.7           3.1            5.6           2.4  Iris-virginica
140            6.9           3.1            5.1           2.3  Iris-virginica
141            5.8           2.7            5.1           1.9  Iris-virginica
142            6.8           3.2            5.9           2.3  Iris-virginica
143            6.7           3.3            5.7           2.5  Iris-virginica
144            6.7           3.0            5.2           2.3  Iris-virginica
145            6.3           2.5            5.0           1.9  Iris-virginica
146            6.5           3.0            5.2           2.0  Iris-virginica
147            6.2           3.4            5.4           2.3  Iris-virginica
148            5.9           3.0            5.1           1.8  Iris-virginica

[149 rows x 5 columns]

# Naive bayes

In [38]:
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [22]:
X = data.drop(['Species'],axis=1)

In [24]:
y = data['Species']

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.33, random_state=42)

In [53]:
#X_train.size
#X_test.size
#y_test.size
y_test.size

50

In [27]:
clf = GaussianNB()

In [28]:
clf.fit(X_train,y_train)

GaussianNB(priors=None)

In [30]:
pred = clf.predict(X_test)

In [51]:
pred

array(['Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-virginica'],
      dtype='<U15')

In [54]:
accuracy_score(y_test, pred)

0.85999999999999999

# support vector machine

In [55]:
from sklearn.svm import SVC

In [56]:
clf = SVC()

In [57]:
clf.fit(X, y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [58]:
pred = clf.predict(X_test)

In [59]:
pred

array(['Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica'], dtype=object)

In [62]:
accuracy_score(y_test, pred)

0.95999999999999996

In [63]:
pd.DataFrame(pred,y_test)

                               0
Species
Iris-versicolor  Iris-versicolor
Iris-setosa          Iris-setosa
Iris-virginica    Iris-virginica
Iris-versicolor  Iris-versicolor
Iris-versicolor   Iris-virginica
Iris-setosa          Iris-setosa
Iris-versicolor  Iris-versicolor
Iris-virginica    Iris-virginica
Iris-versicolor  Iris-versicolor
Iris-versicolor   Iris-virginica
Iris-virginica    Iris-virginica
Iris-setosa          Iris-setosa
Iris-setosa          Iris-setosa
Iris-setosa          Iris-setosa
Iris-setosa          Iris-setosa
Iris-versicolor  Iris-versicolor
Iris-virginica    Iris-virginica
Iris-versicolor  Iris-versicolor
Iris-versicolor  Iris-versicolor
Iris-virginica    Iris-virginica
Iris-setosa          Iris-setosa
Iris-virginica    Iris-virginica
Iris-setosa          Iris-setosa
Iris-virginica    Iris-virginica
Iris-virginica    Iris-virginica
Iris-virginica    Iris-virginica
Iris-virginica    Iris-virginica
Iris-virginica    Iris-virginica
Iris-setosa          Iris-setosa
Iris-setosa          Iris-setosa
Iris-setosa          Iris-setosa
Iris-setosa          Iris-setosa
Iris-versicolor  Iris-versicolor
Iris-setosa          Iris-setosa
Iris-setosa          Iris-setosa
Iris-virginica    Iris-virginica
Iris-versicolor  Iris-versicolor
Iris-setosa          Iris-setosa
Iris-setosa          Iris-setosa
Iris-setosa          Iris-setosa
Iris-virginica    Iris-virginica
Iris-versicolor  Iris-versicolor
Iris-versicolor  Iris-versicolor
Iris-setosa          Iris-setosa
Iris-setosa          Iris-setosa
Iris-versicolor  Iris-versicolor
Iris-virginica    Iris-virginica
Iris-virginica    Iris-virginica
Iris-versicolor  Iris-versicolor
Iris-virginica    Iris-virginica

# Decision tree

In [68]:
from sklearn.model_selection import cross_val_score

In [69]:
from sklearn.tree import DecisionTreeClassifier

In [76]:
clf = DecisionTreeClassifier()

In [99]:
cv = cross_val_score(clf, X, y,cv=50)

c:\users\test\appdata\local\programs\python\python36\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 49 members, which is too few. The minimum number of members in any class cannot be less than n_splits=50.
  % (min_groups, self.n_splits)), Warning)

In [100]:
cv

array([ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
        1.        ,  0.66666667,  1.        ,  1.        ,  1.        ,
        1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
        1.        ,  1.        ,  1.        ,  1.        ,  0.66666667,
        0.66666667,  1.        ,  1.        ,  1.        ,  1.        ,
        1.        ,  1.        ,  0.66666667,  1.        ,  0.66666667,
        1.        ,  1.        ,  1.        ,  0.66666667,  1.        ,
        1.        ,  1.        ,  1.        ,  0.66666667,  1.        ,
        1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
        1.        ,  1.        ,  1.        ,  1.        ,  1.        ])

In [101]:
accuracy_score(y_test, pred)

0.95999999999999996

In [102]:
pd.DataFrame(cv)

           0
0   1.000000
1   1.000000
2   1.000000
3   1.000000
4   1.000000
5   1.000000
6   0.666667
7   1.000000
8   1.000000
9   1.000000
10  1.000000
11  1.000000
12  1.000000
13  1.000000
14  1.000000
15  1.000000
16  1.000000
17  1.000000
18  1.000000
19  0.666667
20  0.666667
21  1.000000
22  1.000000
23  1.000000
24  1.000000
25  1.000000
26  1.000000
27  0.666667
28  1.000000
29  0.666667
30  1.000000
31  1.000000
32  1.000000
33  0.666667
34  1.000000
35  1.000000
36  1.000000
37  1.000000
38  0.666667
39  1.000000
40  1.000000
41  1.000000
42  1.000000
43  1.000000
44  1.000000
45  1.000000
46  1.000000
47  1.000000
48  1.000000
49  1.000000

# Linear regression

In [9]:
data1 = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data')

In [10]:
data1.columns = ['mpg','cylinders','displacement','horsepower','weight','acceleration','model year','origin','car name']

ValueError: Length mismatch: Expected axis has 1 elements, new values have 9 elements

In [11]:
data1

    18.0   8   307.0      130.0      3504.      12.0   70  1\t"chevrolet chevelle malibu"
0    15.0   8   350.0      165.0      3693.      11...
1    18.0   8   318.0      150.0      3436.      11...
2    16.0   8   304.0      150.0      3433.      12...
3    17.0   8   302.0      140.0      3449.      10...
4    15.0   8   429.0      198.0      4341.      10...
5    14.0   8   454.0      220.0      4354.       9...
6    14.0   8   440.0      215.0      4312.       8...
7    14.0   8   455.0      225.0      4425.      10...
8    15.0   8   390.0      190.0      3850.       8...
9    15.0   8   383.0      170.0      3563.      10...
10   14.0   8   340.0      160.0      3609.       8...
11   15.0   8   400.0      150.0      3761.       9...
12   14.0   8   455.0      225.0      3086.      10...
13   24.0   4   113.0      95.00      2372.      15...
14   22.0   6   198.0      95.00      2833.      15...
15   18.0   6   199.0      97.00      2774.      15...
16   21.0   6   200.0      85.00      2587.      16...
17   27.0   4   97.00      88.00      2130.      14...
18   26.0   4   97.00      46.00      1835.      20...
19   25.0   4   110.0      87.00      2672.      17...
20   24.0   4   107.0      90.00      2430.      14...
21   25.0   4   104.0      95.00      2375.      17...
22   26.0   4   121.0      113.0      2234.      12...
23   21.0   6   199.0      90.00      2648.      15...
24   10.0   8   360.0      215.0      4615.      14...
25   10.0   8   307.0      200.0      4376.      15...
26   11.0   8   318.0      210.0      4382.      13...
27   9.0    8   304.0      193.0      4732.      18...
28   27.0   4   97.00      88.00      2130.      14...
29   28.0   4   140.0      90.00      2264.      15...
..                                                 ...
367  27.0   4   112.0      88.00      2640.      18...
368  34.0   4   112.0      88.00      2395.      18...
369  31.0   4   112.0      85.00      2575.      16...
370  29.0   4   135.0      84.00      2525.      16...
371  27.0   4   151.0      90.00      2735.      18...
372  24.0   4   140.0      92.00      2865.      16...
373  23.0   4   151.0      ?          3035.      20...
374  36.0   4   105.0      74.00      1980.      15...
375  37.0   4   91.00      68.00      2025.      18...
376  31.0   4   91.00      68.00      1970.      17...
377  38.0   4   105.0      63.00      2125.      14...
378  36.0   4   98.00      70.00      2125.      17...
379  36.0   4   120.0      88.00      2160.      14...
380  36.0   4   107.0      75.00      2205.      14...
381  34.0   4   108.0      70.00      2245       16...
382  38.0   4   91.00      67.00      1965.      15...
383  32.0   4   91.00      67.00      1965.      15...
384  38.0   4   91.00      67.00      1995.      16...
385  25.0   6   181.0      110.0      2945.      16...
386  38.0   6   262.0      85.00      3015.      17...
387  26.0   4   156.0      92.00      2585.      14...
388  22.0   6   232.0      112.0      2835       14...
389  32.0   4   144.0      96.00      2665.      13...
390  36.0   4   135.0      84.00      2370.      13...
391  27.0   4   151.0      90.00      2950.      17...
392  27.0   4   140.0      86.00      2790.      15...
393  44.0   4   97.00      52.00      2130.      24...
394  32.0   4   135.0      84.00      2295.      11...
395  28.0   4   120.0      79.00      2625.      18...
396  31.0   4   119.0      82.00      2720.      19...

[397 rows x 1 columns]